### ISSUE TITLE
Settings - Device List Columns does not show anything

### ISSUE THREAD

**Issue by cjmair** [kismetwireless/kismet#533]
On the Kismet web UI, selecting Settings then Device List Colums does not display a list of columns.

The web console reports the following error:

> Uncaught TypeError: exports.GetDeviceColumns is not a function
> in js/kismet.ui.js:872

**Comment by bcoles** [comment]
This bug was introduced in df217783e009eaf33875e1b9587edcc5ceeaa6f0.
