### ISSUE TITLE
libprotobuf23 impossible dependency

### ISSUE THREAD

**Issue by Tibladar** [kismetwireless/kismet#299]
Since the update from 2020-04-R3 to 2020-09-R1 the console gets spammed with exceptions:

<details><summary>Log</summary>

```
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtl433", line 11, in <module>
    load_entry_point('KismetCaptureRtl433==2019.9.1', 'console_scripts', 'kismet_cap_sdr_rtl433')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/__init__.py", line 33, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtl433.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtl433", line 11, in <module>
    load_entry_point('KismetCaptureRtl433==2019.9.1', 'console_scripts', 'kismet_cap_sdr_rtl433')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/__init__.py", line 33, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_freaklabs_zigbee", line 11, in <module>
    load_entry_point('KismetCaptureFreaklabsZigbee==2018.7.0', 'console_scripts', 'kismet_cap_freaklabs_zigbee')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/__init__.py", line 64, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/kismetexternal/__init__.py", line 36, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_freaklabs_zigbee.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_freaklabs_zigbee", line 11, in <module>
    load_entry_point('KismetCaptureFreaklabsZigbee==2018.7.0', 'console_scripts', 'kismet_cap_freaklabs_zigbee')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/__init__.py", line 64, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/kismetexternal/__init__.py", line 36, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureFreaklabsZigbee/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtlamr", line 11, in <module>
    load_entry_point('KismetCaptureRtlamr==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtlamr')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
Traceback (most recent call last):
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/__init__.py", line 39, in <module>
  File "/usr/bin/kismet_cap_sdr_rtladsb", line 11, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/__init__.py", line 38, in <module>
    load_entry_point('KismetCaptureRtladsb==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtladsb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtlamr.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtlamr", line 11, in <module>
    load_entry_point('KismetCaptureRtlamr==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtlamr')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/__init__.py", line 38, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
    with os.fdopen(os.open(pr_filename,
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/__init__.py", line 39, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtladsb.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtladsb", line 11, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/__init__.py", line 38, in <module>
    load_entry_point('KismetCaptureRtladsb==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtladsb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/__init__.py", line 38, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtl433", line 11, in <module>
    load_entry_point('KismetCaptureRtl433==2019.9.1', 'console_scripts', 'kismet_cap_sdr_rtl433')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/__init__.py", line 33, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtl433.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtl433", line 11, in <module>
    load_entry_point('KismetCaptureRtl433==2019.9.1', 'console_scripts', 'kismet_cap_sdr_rtl433')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/__init__.py", line 33, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtl433/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtlamr", line 11, in <module>
    load_entry_point('KismetCaptureRtlamr==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtlamr')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/__init__.py", line 39, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtlamr.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtlamr", line 11, in <module>
    load_entry_point('KismetCaptureRtlamr==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtlamr')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/__init__.py", line 39, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtlamr/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtladsb", line 11, in <module>
    load_entry_point('KismetCaptureRtladsb==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtladsb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/__init__.py", line 38, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kismet_cap_sdr_rtladsb.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kismet_cap_sdr_rtladsb", line 11, in <module>
    load_entry_point('KismetCaptureRtladsb==2019.10.1', 'console_scripts', 'kismet_cap_sdr_rtladsb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/__init__.py", line 38, in <module>
    from . import kismetexternal
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/__init__.py", line 38, in <module>
    from . import kismet_pb2
  File "/usr/lib/python3/dist-packages/KismetCaptureRtladsb/kismetexternal/kismet_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

```

</details>

Maybe it's because of:
```
kismet-core/now 2020-04-R3 amd64  [Installed,updatable to: 2020-09-R1]
kismet-core : Depends on: libprotobuf23 but is not installable
```
libprotobuf23 only exists on groovy (Ubuntu 20.10), not focal (Ubuntu 20.04)

OS: Linux Mint 20
Kismet: 2020-09-R1 from official repo

**Comment by Tibladar** [comment]
A purge & clean install did the trick even though I don't know what caused it.
